theme: jekyll-theme-slate
title: Eds Tech Tips
description: I am a graduate from Kean University with a Bachelor of Science in Computer Science. I have also acquired my CompTIA Security+ Certificate. I am interested in learning about Cyber Security, and will be documenting everything here.